version: "3.9"
services:
    postgres:
        image: postgres:13.2
        container_name: postgres_container
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=AgilePoker
            - POSTGRES_USER=palomaqsnunes
        ports: 
            - "5432:5432"
        networks: 
            - postgres-network  
        volumes: 
            - /var/lib/postgresql/data
networks: 
    postgres-network:
        driver: bridge

